import type { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Classic Denim Jacket',
    price: 6500,
    originalPrice: 7599,
    images: [
      'https://picsum.photos/seed/picsum1-1/800/1000',
      'https://picsum.photos/seed/picsum1-2/800/1000',
      'https://picsum.photos/seed/picsum1-3/800/1000',
    ],
    description: 'A timeless denim jacket that belongs in every wardrobe. Made with 100% premium cotton for a comfortable fit that gets better with age.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Vintage Blue', 'Black Wash'],
    category: 'Jackets',
  },
  {
    id: 2,
    name: 'Organic Cotton Tee',
    price: 1800,
    originalPrice: 2199,
    images: [
      'https://picsum.photos/seed/picsum2-1/800/1000',
      'https://picsum.photos/seed/picsum2-2/800/1000',
      'https://picsum.photos/seed/picsum2-3/800/1000',
    ],
    description: 'Ultra-soft and breathable, this t-shirt is made from 100% organic cotton. A perfect staple for any casual occasion.',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: ['White', 'Heather Gray', 'Navy'],
    category: 'T-Shirts',
  },
  {
    id: 3,
    name: 'Slim-Fit Chinos',
    price: 4850,
    images: [
      'https://picsum.photos/seed/picsum3-1/800/1000',
      'https://picsum.photos/seed/picsum3-2/800/1000',
      'https://picsum.photos/seed/picsum3-3/800/1000',
    ],
    description: 'Look sharp and feel comfortable with our slim-fit chinos. A versatile pant that can be dressed up or down.',
    sizes: ['30', '32', '34', '36'],
    colors: ['Khaki', 'Olive Green', 'Charcoal'],
    category: 'Pants',
  },
  {
    id: 4,
    name: 'Wool Blend Peacoat',
    price: 15500,
    originalPrice: 18500,
    images: [
      'https://picsum.photos/seed/picsum4-1/800/1000',
      'https://picsum.photos/seed/picsum4-2/800/1000',
      'https://picsum.photos/seed/picsum4-3/800/1000',
    ],
    description: 'Stay warm and stylish in our classic double-breasted peacoat. Crafted from a warm wool blend for ultimate comfort during colder months.',
    sizes: ['S', 'M', 'L'],
    colors: ['Navy', 'Camel'],
    category: 'Jackets',
  },
  {
    id: 5,
    name: 'Linen Button-Down Shirt',
    price: 4500,
    images: [
      'https://picsum.photos/seed/picsum5-1/800/1000',
      'https://picsum.photos/seed/picsum5-2/800/1000',
      'https://picsum.photos/seed/picsum5-3/800/1000',
    ],
    description: 'Lightweight and breathable, this linen shirt is perfect for warm weather. Features a classic collar and a relaxed fit.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Light Blue', 'White', 'Striped'],
    category: 'Shirts',
  },
  {
    id: 6,
    name: 'Performance Joggers',
    price: 5200,
    originalPrice: 6200,
    images: [
      'https://picsum.photos/seed/picsum6-1/800/1000',
      'https://picsum.photos/seed/picsum6-2/800/1000',
      'https://picsum.photos/seed/picsum6-3/800/1000',
    ],
    description: 'Engineered for comfort and style, these joggers are perfect for workouts or lounging. Made with moisture-wicking fabric.',
    sizes: ['S', 'M', 'L'],
    colors: ['Black', 'Graphite'],
    category: 'Pants',
  },
  {
    id: 7,
    name: 'Cashmere Crewneck Sweater',
    price: 12500,
    images: [
      'https://picsum.photos/seed/picsum7-1/800/1000',
      'https://picsum.photos/seed/picsum7-2/800/1000',
      'https://picsum.photos/seed/picsum7-3/800/1000',
    ],
    description: 'Experience luxury with our 100% cashmere sweater. Incredibly soft, warm, and lightweight, it\'s an investment piece you\'ll cherish.',
    sizes: ['M', 'L', 'XL'],
    colors: ['Charcoal', 'Oatmeal', 'Burgundy'],
    category: 'Sweaters',
  },
  {
    id: 8,
    name: 'Leather Ankle Boots',
    price: 8500,
    originalPrice: 9900,
    images: [
      'https://picsum.photos/seed/picsum8-1/800/1000',
      'https://picsum.photos/seed/picsum8-2/800/1000',
      'https://picsum.photos/seed/picsum8-3/800/1000',
    ],
    description: 'Versatile and chic, these leather ankle boots will elevate any outfit. Features a comfortable block heel and side zipper.',
    sizes: ['7', '8', '9', '10'],
    colors: ['Black', 'Brown'],
    category: 'Shoes',
  },
  {
    id: 9,
    name: 'Graphic Print Hoodie',
    price: 5500,
    images: [
      'https://picsum.photos/seed/picsum9-1/800/1000',
      'https://picsum.photos/seed/picsum9-2/800/1000',
      'https://picsum.photos/seed/picsum9-3/800/1000',
    ],
    description: 'A comfortable fleece hoodie with a modern graphic print. Perfect for a relaxed, street-style look.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Heather Gray', 'Black'],
    category: 'Sweaters',
  },
  {
    id: 10,
    name: 'Tailored Wool Trousers',
    price: 8900,
    images: [
      'https://picsum.photos/seed/picsum10-1/800/1000',
      'https://picsum.photos/seed/picsum10-2/800/1000',
      'https://picsum.photos/seed/picsum10-3/800/1000',
    ],
    description: 'Impeccably tailored trousers made from fine wool. A sophisticated choice for work or formal events.',
    sizes: ['30', '32', '34', '36'],
    colors: ['Gray', 'Navy'],
    category: 'Pants',
  },
  {
    id: 11,
    name: 'Puffer Vest',
    price: 6800,
    originalPrice: 7800,
    images: [
      'https://picsum.photos/seed/picsum11-1/800/1000',
      'https://picsum.photos/seed/picsum11-2/800/1000',
      'https://picsum.photos/seed/picsum11-3/800/1000',
    ],
    description: 'A lightweight yet warm puffer vest, perfect for layering. Water-resistant shell and responsibly sourced down insulation.',
    sizes: ['M', 'L', 'XL'],
    colors: ['Red', 'Black', 'Forest Green'],
    category: 'Jackets',
  },
  {
    id: 12,
    name: 'Minimalist Leather Sneakers',
    price: 11500,
    images: [
      'https://picsum.photos/seed/picsum12-1/800/1000',
      'https://picsum.photos/seed/picsum12-2/800/1000',
      'https://picsum.photos/seed/picsum12-3/800/1000',
    ],
    description: 'Clean, simple, and stylish. These premium leather sneakers are designed for everyday comfort and versatility.',
    sizes: ['8', '9', '10', '11', '12'],
    colors: ['White', 'Black'],
    category: 'Shoes',
  },
  {
    id: 13,
    name: 'Silk Blend Scarf',
    price: 2500,
    images: [
      'https://picsum.photos/seed/picsum13-1/800/1000',
      'https://picsum.photos/seed/picsum13-2/800/1000',
      'https://picsum.photos/seed/picsum13-3/800/1000',
    ],
    description: 'A beautiful and soft scarf made from a luxurious silk blend. The perfect accessory to add a pop of color to any outfit.',
    sizes: ['One Size'],
    colors: ['Floral', 'Paisley', 'Geometric'],
    category: 'Accessories',
  }
];